### ISSUE TITLE
My Error List

### ISSUE THREAD

**Issue by Sea-n** [TelegramBotAPI/errors#2]
Hey, here is what I found from my error log of 1x bots 😜

<details><summary><b>400 Bad Request</b> (32 error type)</summary>
<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: BOT_SCORE_NOT_MODIFIED"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: CHAT_ADMIN_REQUIRED"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: ENTITY_MENTION_USER_INVALID"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: MESSAGE_ID_INVALID"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: QUERY_ID_INVALID"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: RESULT_TYPE_INVALID"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: USER_ID_INVALID"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't demote chat creator"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset X"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't parse entities in message text: Can't found end tag corresponding to start tag at byte offset X"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't parse entities in message text: Expected end tag at byte offset X"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't parse entities in message text: Expected equal sign in declaration of attribute of the tag \"foo\" at byte offset X"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't parse entities in message text: Unclosed end tag at byte offset X"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't parse entities in message text: Unclosed start tag at byte offset X"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't parse entities in message text: Unexpected end of name token at byte offset X"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't parse entities in message text: Unexpected end tag at byte offset X"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't parse entities in message text: Unmatched end tag at byte offset X, expected \"</foo>\", found\"</bar>\""
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: can't parse entities in message text: Unsupported start tag foo at byte offset X"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: channel members are unavailable"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: chat not found"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: failed to get HTTP URL content"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: have no rights to send a message"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: message can't be edited"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: message can't be forwarded"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: message is not modified"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: message must be non-empty"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: message text is empty"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: message to delete not found"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: message to forward not found"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: reply message not found"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: wrong file identifier/HTTP URL specified"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: wrong persistent file_id specified: can't unserialize it. Wrong last symbol"
}
</pre>
</details>

<details><summary><b>Others</b> (9 error type)</summary>
<pre>
{
  "ok": false,
  "error_code": 401,
  "description": "Unauthorized"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 403,
  "description": "Forbidden: bot can't initiate conversation with a user"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 403,
  "description": "Forbidden: bot can't send messages to bots"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 403,
  "description": "Forbidden: bot is not a member of the supergroup chat"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 403,
  "description": "Forbidden: bot was blocked by the user"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 403,
  "description": "Forbidden: bot was kicked from the group chat"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 403,
  "description": "Forbidden: bot was kicked from the supergroup chat"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 409,
  "description": "Conflict: can't use getUpdates method while webhook is active"
}
</pre>

<pre>
{
  "ok": false,
  "error_code": 429,
  "description": "Too Many Requests: retry after X",
  "parameters": {
    "retry_after": "X"
  }
}
</pre>

</details>

**Comment by unreal4u** [comment]
nice! Thanks, will integrate them in the main repo one of these days

**Comment by develowper** [comment]
any solution?
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: CHAT_ADMIN_REQUIRED"
}

i get this with magnetgrambot for @perspoliswallpapers

**Comment by Hariraj1029** [comment]
{
  "ok": false,
  "error_code": 403,
  "description": "Forbidden: bot can't initiate conversation with a user"
}


The user has to initiate the bot atleast once for the bot to initiate the conversation with that user. So the user has to message the bot then the error mentioned above won't arise
