### ISSUE TITLE
Pretty Print JSON

### ISSUE THREAD

**Issue by Sea-n** [TelegramBotAPI/errors#3]
For instance, [429 Too Many Request](https://github.com/TelegramBotAPI/errors/blob/master/json/too-many-requests.json) can be:

```json
{
  "ok": false,
  "error_code": 429,
  "description": "Too Many Requests: retry after X",
  "parameters": {
    "retry_after": "X"
  }
}
```

**Comment by unreal4u** [comment]
I was thinking of linking this repo to a github.io hosted page where you can effectively see nice formatted output, but have to find time to do this :)
